name: Docker Image CI

on:
  push:
    branches: [ main ]
  release:
    types:
      - published 

jobs:

  build:
    if: "!contains(github.event.head_commit.message,'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: docker login
#       env:
#         DOCKER_USER: ${{secrets.DOCKER_USER}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       run: |
#           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: docker build
      run: docker build . --file Dockerfile --tag sushantjha/grpc_facereconition_server_core
#     - name: docker push
#       run: |
#         docker push docker.io/sushantjha/grpc_facereconition_server_core

